class AppStrings {
  static const Map<String, Map<String, String>> languages = {
    'id': {
      'dashboard': 'Dashboard',
      'products': 'Produk',
      'categories': 'Kategori',
      'menu': 'Menu',
      'settings': 'Pengaturan',
      'total_revenue': 'Total Omset',
      'transactions': 'Transaksi',
      'products_sold': 'Produk Terjual',
      'average': 'Rata-rata',
      'top_products': 'Produk Terlaris',
      'recent_transactions': 'Transaksi Terbaru',
      'sales_by_category': 'Penjualan per Kategori',
      'change_language': 'Ganti Bahasa',
      'select_language': 'Pilih Bahasa',
      'logout': 'Keluar',
      'cancel': 'Batal',
      'confirm': 'Konfirmasi',
      'logout_confirm': 'Apakah Anda yakin ingin keluar?',
      'week': 'Minggu Ini',
      'month': 'Bulan Ini',
      'year': 'Tahun Ini',
      'today': 'Hari Ini',
    },
    'en': {
      'dashboard': 'Dashboard',
      'products': 'Products',
      'categories': 'Categories',
      'menu': 'Menu',
      'settings': 'Settings',
      'total_revenue': 'Total Revenue',
      'transactions': 'Transactions',
      'products_sold': 'Products Sold',
      'average': 'Average',
      'top_products': 'Top Products',
      'recent_transactions': 'Recent Transactions',
      'sales_by_category': 'Sales by Category',
      'change_language': 'Change Language',
      'select_language': 'Select Language',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'logout_confirm': 'Are you sure you want to logout?',
      'week': 'This Week',
      'month': 'This Month',
      'year': 'This Year',
      'today': 'Today',
    },
  };
}